### GET /
GET http://localhost:8080 HTTP/1.1

### POST /auth/signup
POST http://localhost:8080/auth/signup HTTP/1.1
Content-Type: application/json

{
  	"username": "jasnacvikl",
  	"password": "Jasna123!",
  	"confirm_password": "Jasna123!"
}

### POST /auth/signin
POST http://localhost:8080/auth/signin HTTP/1.1
Content-Type: application/json

{
  	"username": "johnguzej", 
  	"password": "John123!" 
}

### GET /me
GET http://localhost:8080/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzN2M1YjZlMS1hZmU5LTQyZmQtOWQ3Ni00ZmI4MzlmOTVkODciLCJ1c2VybmFtZSI6ImpvaG5ndXplaiIsImlhdCI6MTcyNjE3MjEzMiwiZXhwIjoxNzI2MTczMDMyfQ.CbMbXYk4o4S7q892fzURe0oI_LXCoZwERnjOVYle-r4

### PATCH /me/update-password
PATCH  http://localhost:8080/me/update-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzN2M1YjZlMS1hZmU5LTQyZmQtOWQ3Ni00ZmI4MzlmOTVkODciLCJ1c2VybmFtZSI6ImpvaG5ndXplaiIsImlhdCI6MTcyNjE3MjEzMiwiZXhwIjoxNzI2MTczMDMyfQ.CbMbXYk4o4S7q892fzURe0oI_LXCoZwERnjOVYle-r4

{
  	"password": "John123!", 
  	"confirm_password": "John123!" 
}