### GET /
GET http://localhost:8080 HTTP/1.1

### POST /auth/signup
POST http://localhost:8080/auth/signup HTTP/1.1
Content-Type: application/json

{
  	"username": "jasnacvikl",
  	"password": "Jasna123!",
  	"confirm_password": "Jasna123!"
}

### POST /auth/signin
POST http://localhost:8080/auth/signin HTTP/1.1
Content-Type: application/json

{
  	"username": "johnguzej", 
  	"password": "John123!" 
}

### GET /me
GET http://localhost:8080/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzN2M1YjZlMS1hZmU5LTQyZmQtOWQ3Ni00ZmI4MzlmOTVkODciLCJ1c2VybmFtZSI6ImpvaG5ndXplaiIsImlhdCI6MTcyNjE3MjEzMiwiZXhwIjoxNzI2MTczMDMyfQ.CbMbXYk4o4S7q892fzURe0oI_LXCoZwERnjOVYle-r4

### PATCH /me/update-password
PATCH  http://localhost:8080/me/update-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzN2M1YjZlMS1hZmU5LTQyZmQtOWQ3Ni00ZmI4MzlmOTVkODciLCJ1c2VybmFtZSI6ImpvaG5ndXplaiIsImlhdCI6MTcyNjE3MjEzMiwiZXhwIjoxNzI2MTczMDMyfQ.CbMbXYk4o4S7q892fzURe0oI_LXCoZwERnjOVYle-r4

{
  	"password": "John123!", 
  	"confirm_password": "John123!" 
}

### GET /auctions
GET http://localhost:8080/auctions HTTP/1.1

### POST /me/auction
POST http://localhost:8080/me/auction HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzN2M1YjZlMS1hZmU5LTQyZmQtOWQ3Ni00ZmI4MzlmOTVkODciLCJ1c2VybmFtZSI6ImpvaG5ndXplaiIsImlhdCI6MTcyNjQyNTQ3MiwiZXhwIjoxNzI2NDI2MzcyfQ.FKG6DIFJgMgzSCPBs47eJigQZe1TKFqo81Gz4W_8xlc

{
	"title": "Test auction 12341",
	"description": "This is a posting of a test auction",
	"starting_price": 100,
	"auction_duration_hrs": 20
}

### PATCH /me/auction/:id
PATCH http://localhost:8080/me/auction/734ec6f4-4fef-44f2-a2c9-5c3334989070 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzN2M1YjZlMS1hZmU5LTQyZmQtOWQ3Ni00ZmI4MzlmOTVkODciLCJ1c2VybmFtZSI6ImpvaG5ndXplaiIsImlhdCI6MTcyNjQyNTQ3MiwiZXhwIjoxNzI2NDI2MzcyfQ.FKG6DIFJgMgzSCPBs47eJigQZe1TKFqo81Gz4W_8xlc

{
	"is_active": true
}